import { existsSync } from 'node:fs';
import type { SiteInput } from '@pm2-launcher/shared';
import { ECOSYSTEM_PATH, ensureStateDir } from './config';

export type EcosystemApp = SiteInput;

const HEADER = `// Auto-generated by pm2-launcher.
// Edit via the UI at http://127.0.0.1:<port>.
// Hand-edits will be overwritten on the next mutation.

`;

function indent(text: string, prefix: string): string {
  return text
    .split('\n')
    .map((line) => (line.length ? prefix + line : line))
    .join('\n');
}

function serializeValue(value: unknown): string {
  if (value === undefined) return 'undefined';
  if (value === null) return 'null';
  if (typeof value === 'string') return JSON.stringify(value);
  if (typeof value === 'number' || typeof value === 'boolean') return String(value);
  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const items = value.map((v) => indent(serializeValue(v), '    ')).join(',\n');
    return `[\n${items}\n  ]`;
  }
  if (typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>).filter(
      ([, v]) => v !== undefined,
    );
    if (entries.length === 0) return '{}';
    const lines = entries.map(
      ([k, v]) => `      ${JSON.stringify(k)}: ${serializeValue(v)}`,
    );
    return `{\n${lines.join(',\n')}\n    }`;
  }
  return JSON.stringify(value);
}

function appToConfig(app: EcosystemApp): Record<string, unknown> {
  const env: Record<string, string> = { ...app.env, PM2_LAUNCHER: '1' };
  if (app.port !== undefined) env.PORT = String(app.port);

  return {
    name: app.name,
    cwd: app.cwd,
    script: app.script,
    interpreter: app.interpreter,
    args: app.args,
    instances: app.instances,
    // cluster mode pins to node — force fork unless user explicitly scales out
    exec_mode: app.instances > 1 ? 'cluster' : 'fork',
    autorestart: app.autorestart,
    env,
  };
}

export function serializeEcosystem(apps: EcosystemApp[]): string {
  const items = apps.map((app) => {
    const cfg = appToConfig(app);
    const lines = Object.entries(cfg)
      .filter(([, v]) => v !== undefined)
      .map(([k, v]) => `    ${JSON.stringify(k)}: ${serializeValue(v)}`);
    return `  {\n${lines.join(',\n')}\n  }`;
  });
  return `${HEADER}module.exports = {\n  apps: [\n${items.join(',\n')}\n  ]\n};\n`;
}

export async function readEcosystem(): Promise<EcosystemApp[]> {
  if (!existsSync(ECOSYSTEM_PATH)) return [];
  const proc = Bun.spawn(
    [
      'node',
      '-e',
      `process.stdout.write(JSON.stringify(require(${JSON.stringify(ECOSYSTEM_PATH)})))`,
    ],
    { stdout: 'pipe', stderr: 'pipe' },
  );
  const [stdout, stderr] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
  ]);
  await proc.exited;
  if (proc.exitCode !== 0) {
    throw new Error(`Failed to read ${ECOSYSTEM_PATH}: ${stderr}`);
  }
  const parsed = JSON.parse(stdout) as { apps?: unknown[] };
  const apps = Array.isArray(parsed.apps) ? parsed.apps : [];
  return apps.map(rawToInput);
}

function rawToInput(raw: unknown): EcosystemApp {
  const r = raw as Record<string, unknown>;
  const env = (r.env as Record<string, string>) ?? {};
  const portRaw = env.PORT;
  const port = portRaw !== undefined ? Number(portRaw) : undefined;
  const userEnv = { ...env };
  delete userEnv.PORT;
  delete userEnv.PM2_LAUNCHER;
  return {
    name: String(r.name ?? ''),
    cwd: String(r.cwd ?? ''),
    script: r.script ? String(r.script) : undefined,
    interpreter: r.interpreter ? String(r.interpreter) : undefined,
    args: r.args ? String(r.args) : undefined,
    port: port !== undefined && !Number.isNaN(port) ? port : undefined,
    env: userEnv,
    autorestart: r.autorestart !== false,
    instances: typeof r.instances === 'number' ? r.instances : 1,
  };
}

export async function writeEcosystem(apps: EcosystemApp[]): Promise<void> {
  ensureStateDir();
  await Bun.write(ECOSYSTEM_PATH, serializeEcosystem(apps));
}

export async function upsertApp(app: EcosystemApp): Promise<EcosystemApp[]> {
  const apps = await readEcosystem();
  const idx = apps.findIndex((a) => a.name === app.name);
  if (idx >= 0) apps[idx] = app;
  else apps.push(app);
  await writeEcosystem(apps);
  return apps;
}

export async function removeApp(name: string): Promise<EcosystemApp[]> {
  const apps = (await readEcosystem()).filter((a) => a.name !== name);
  await writeEcosystem(apps);
  return apps;
}

export async function getApp(name: string): Promise<EcosystemApp | null> {
  const apps = await readEcosystem();
  return apps.find((a) => a.name === name) ?? null;
}
