#!/usr/bin/env bun
/**
 * Install / refresh the pm2-launcher entry in PM2.
 *
 * - Locks a port via cl.broberg.dk on first run, persists in ~/.pm2-launcher/config.json
 * - Generates ~/.pm2-launcher/ecosystem.config.cjs with the launcher app
 *   (preserving any other launcher-managed apps that already exist)
 * - Starts/reloads the launcher in PM2 and saves the dump
 */

import { existsSync, mkdirSync } from 'node:fs';
import { homedir } from 'node:os';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, '..');
const STATE_DIR = join(homedir(), '.pm2-launcher');
const CONFIG_PATH = join(STATE_DIR, 'config.json');
const ECOSYSTEM_PATH = join(STATE_DIR, 'ecosystem.config.cjs');

const CL_BASE = 'https://cl.broberg.dk';
const CL_TOKEN = process.env.CL_API_TOKEN ?? '2e101df079121aefca3e38cbe7885644a62e001d7ea36f15a9719f4681354929';

const LAUNCHER_NAME = 'pm2-launcher';

function ensureDir(): void {
  if (!existsSync(STATE_DIR)) mkdirSync(STATE_DIR, { recursive: true });
}

async function readJson<T>(path: string): Promise<T | null> {
  if (!existsSync(path)) return null;
  return JSON.parse(await Bun.file(path).text()) as T;
}

async function fetchVacantPort(): Promise<number> {
  const res = await fetch(`${CL_BASE}/api/vacant-port`);
  if (!res.ok) throw new Error(`vacant-port HTTP ${res.status}`);
  const json = (await res.json()) as { port: number };
  if (typeof json.port !== 'number') throw new Error('bad vacant-port response');
  return json.port;
}

async function reportPort(port: number): Promise<void> {
  const res = await fetch(`${CL_BASE}/api/apps/report-port`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${CL_TOKEN}`,
    },
    body: JSON.stringify({ localPath: REPO_ROOT, port }),
  });
  if (!res.ok) {
    console.warn(`[install] report-port failed (${res.status}) — continuing.`);
  }
}

async function lockPort(): Promise<{ port: number; host: string }> {
  ensureDir();
  const cfg = await readJson<{ port?: number; host?: string }>(CONFIG_PATH);
  if (cfg?.port) {
    return { port: cfg.port, host: cfg.host ?? '127.0.0.1' };
  }
  const port = await fetchVacantPort();
  const next = { port, host: '127.0.0.1' };
  await Bun.write(CONFIG_PATH, JSON.stringify(next, null, 2) + '\n');
  await reportPort(port).catch(() => undefined);
  return next;
}

async function loadExistingApps(): Promise<Array<Record<string, unknown>>> {
  if (!existsSync(ECOSYSTEM_PATH)) return [];
  const proc = Bun.spawn(
    [
      'node',
      '-e',
      `process.stdout.write(JSON.stringify(require(${JSON.stringify(ECOSYSTEM_PATH)})))`,
    ],
    { stdout: 'pipe', stderr: 'pipe' },
  );
  const text = await new Response(proc.stdout).text();
  await proc.exited;
  if (proc.exitCode !== 0) return [];
  const parsed = JSON.parse(text) as { apps?: Array<Record<string, unknown>> };
  return parsed.apps ?? [];
}

function serializeApps(apps: Array<Record<string, unknown>>): string {
  const lines = apps.map((app) => {
    const entries = Object.entries(app).filter(([, v]) => v !== undefined);
    return (
      '  {\n' +
      entries
        .map(([k, v]) => `    ${JSON.stringify(k)}: ${JSON.stringify(v, null, 2).split('\n').join('\n    ')}`)
        .join(',\n') +
      '\n  }'
    );
  });
  return (
    '// Auto-generated by pm2-launcher.\n' +
    '// Edit via the UI; hand-edits are overwritten on the next mutation.\n\n' +
    'module.exports = {\n  apps: [\n' +
    lines.join(',\n') +
    '\n  ]\n};\n'
  );
}

async function writeEcosystem(port: number, host: string): Promise<void> {
  const existing = await loadExistingApps();
  const filtered = existing.filter((a) => a.name !== LAUNCHER_NAME);

  const launcher: Record<string, unknown> = {
    name: LAUNCHER_NAME,
    cwd: REPO_ROOT,
    // launch.sh execs bun directly, sidestepping PM2's bun-container
    // (ProcessContainerForkBun.js) which can't require() our ESM tree.
    script: 'apps/server/launch.sh',
    interpreter: 'none',
    exec_mode: 'fork',
    instances: 1,
    autorestart: true,
    env: {
      PORT: String(port),
      HOST: host,
      PM2_LAUNCHER: '1',
    },
  };

  const apps = [launcher, ...filtered];
  await Bun.write(ECOSYSTEM_PATH, serializeApps(apps));
}

async function pmCommand(args: string[]): Promise<void> {
  const proc = Bun.spawn(['pm2', ...args], {
    stdout: 'inherit',
    stderr: 'inherit',
  });
  await proc.exited;
  if (proc.exitCode !== 0) {
    throw new Error(`pm2 ${args.join(' ')} exited ${proc.exitCode}`);
  }
}

async function main(): Promise<void> {
  console.log('[install] locking port…');
  const { port, host } = await lockPort();
  console.log(`[install] port=${port} host=${host}`);

  console.log('[install] writing ecosystem config…');
  await writeEcosystem(port, host);
  console.log(`[install] wrote ${ECOSYSTEM_PATH}`);

  console.log('[install] starting/reloading via pm2…');
  // delete first so script/cwd/env updates take effect cleanly
  await pmCommand(['delete', LAUNCHER_NAME]).catch(() => undefined);
  await pmCommand(['start', ECOSYSTEM_PATH, '--only', LAUNCHER_NAME]);
  await pmCommand(['save']);

  console.log('');
  console.log(`✔ pm2-launcher running at http://${host}:${port}`);
  console.log('  Logs:  pm2 logs pm2-launcher');
  console.log('  Stop:  pm2 stop pm2-launcher');
}

main().catch((err) => {
  console.error('[install] failed:', err);
  process.exit(1);
});
